#ifndef JOS_INC_TRAP_H
#define JOS_INC_TRAP_H

// Trap numbers
// These are processor defined:
#define T_DIVIDE     0		// divide error除数为0异常
#define T_DEBUG      1		// debug exception调试异常
#define T_NMI        2		// non-maskable interrupt不可屏蔽中断（硬件中断）
#define T_BRKPT      3		// breakpoint断点
#define T_OFLOW      4		// overflow溢出
#define T_BOUND      5		// bounds check边界检查
#define T_ILLOP      6		// illegal opcode非法的操作码
#define T_DEVICE     7		// device not available设备无法访问
#define T_DBLFLT     8		// double fault在CPU处理异常时出现的异常
/* #define T_COPROC  9 */	// reserved (not generated by recent processors)
#define T_TSS       10		// invalid task switch segment无效的任务状态段TSSTSS
#define T_SEGNP     11		// segment not present段不存在
#define T_STACK     12		// stack exception栈异常
#define T_GPFLT     13		// general protection fault保护异常
#define T_PGFLT     14		// page fault页缺失
/* #define T_RES    15 */	// reserved
#define T_FPERR     16		// floating point error浮点指针错误
#define T_ALIGN     17		// aligment check权限（？对其检查
#define T_MCHK      18		// machine check机器检查
#define T_SIMDERR   19		// SIMD floating point errorSTMD浮点指针错误

// These are arbitrarily chosen, but with care not to overlap
// processor defined exceptions or interrupt vectors.
#define T_SYSCALL   48		// system call系统调用
#define T_DEFAULT   500		// catchall任意错误

#define IRQ_OFFSET	32	// IRQ 0 corresponds to int IRQ_OFFSET

// Hardware IRQ numbers. We receive these as (IRQ_OFFSET+IRQ_WHATEVER)
#define IRQ_TIMER        0
#define IRQ_KBD          1
#define IRQ_SERIAL       4
#define IRQ_SPURIOUS     7
#define IRQ_IDE         14
#define IRQ_ERROR       19

#ifndef __ASSEMBLER__

#include <inc/types.h>

struct PushRegs {
	/* registers as pushed by pusha */
	uint32_t reg_edi;
	uint32_t reg_esi;
	uint32_t reg_ebp;
	uint32_t reg_oesp;		/* Useless */
	uint32_t reg_ebx;
	uint32_t reg_edx;
	uint32_t reg_ecx;
	uint32_t reg_eax;
} __attribute__((packed));

struct Trapframe {
	struct PushRegs tf_regs;
	uint16_t tf_es;
	uint16_t tf_padding1;
	uint16_t tf_ds;
	uint16_t tf_padding2;
	uint32_t tf_trapno;
	/* below here defined by x86 hardware */
	uint32_t tf_err;
	uintptr_t tf_eip;
	uint16_t tf_cs;
	uint16_t tf_padding3;
	uint32_t tf_eflags;
	/* below here only when crossing rings, such as from user to kernel */
	uintptr_t tf_esp;
	uint16_t tf_ss;
	uint16_t tf_padding4;
} __attribute__((packed));


#endif /* !__ASSEMBLER__ */

#endif /* !JOS_INC_TRAP_H */
